[sources.cve]
id = "CVE-2023-38545"
url = "https://cveawg.mitre.org/api/cve/CVE-2020-9493"
published = "2021-06-16T07:30:11Z"
modified = "2022-01-18T18:06:18Z"

[sources.github]
id = "GHSA-7xw9-w465-6x42"
url = "https://raw.githubusercontent.com/github/advisory-database/main/advisories/unreviewed/2023/10/GHSA-7xw9-w465-6x42/GHSA-7xw9-w465-6x42.json"
published = "2023-10-18T06:30:30Z"
modified = "2023-11-16T03:30:19Z"

[sources.curl]
id = "CURL-CVE-2023-38545"
url = "https://curl.se/docs/CVE-2023-38545.json"
published = "2023-10-11T08:00:00.00Z"
modified = "2023-11-19T16:44:33.00Z"

# TODO: The CURL vulnerability source indicates whether the library (libcurl), command line tool, 
# or both are affected by a particular vulnerability and it would be useful to capture that here 
# somehow
[[affected.generic]]
name = "curl"

[[affected.generic.version.ranges]]
introduced = "7.69.0"
fixed = "8.4.0"

[[affected.github]]
user = "curl"
repository = "curl"

[[affected.github.version.ranges]]
introduced = "4a4b63daaa01ef59b131d91e8e6e6dfe275c0f08"
fixed = "fb4415d8aee6c1045be932a34fe6107c2f5ed147"
