[sources.cve]
id = "CVE-2020-9493"
url = "https://cveawg.mitre.org/api/cve/CVE-2020-9493"
published = 2021-06-16T07:30:11Z
modified = 2022-01-18T18:06:18Z

[sources.github]
id = "GHSA-prp9-9gxw-38j8"
url = "https://raw.githubusercontent.com/github/advisory-database/main/advisories/unreviewed/2022/05/GHSA-prp9-9gxw-38j8/GHSA-prp9-9gxw-38j8.json"
published = 2022-05-24T19:05:32Z
modified = 2022-05-24T19:05:32Z

# The log4j:apache-chainsaw artifact is not technically distributed on maven central; therefore, GitHub will
# not currently accept this update per https://github.com/github/advisory-database/pull/2630/; however, 
# chainsaw was packaged into early distributions of log4j and is identifiable by this distinct maven identifier 
# so treat it as a distinct component.
[[affected.maven]]
group_id = "log4j"
artifact_id = "apache-chainsaw"

[[affected.maven.version.ranges]]
fixed = "2.1.0"
