[sources.cve]
id = "CVE-2023-38545"
url = "https://cveawg.mitre.org/api/cve/CVE-2024-24783"
published = 2024-03-05T22:22:26.647Z
modified = 2024-03-05T22:22:26.647Z

[sources.github]
id = "GHSA-3q2c-pvp5-3cqp"
url = "https://raw.githubusercontent.com/github/advisory-database/main/advisories/unreviewed/2024/03/GHSA-3q2c-pvp5-3cqp/GHSA-3q2c-pvp5-3cqp.json"
published = 2024-03-06T00:31:26Z
modified = 2024-03-06T00:31:26Z

[sources.go]
id = "GO-2024-2598"
url = "https://vuln.go.dev/ID/GO-2024-2598.json"
published = 2024-03-05T22:14:58Z
modified = 2024-03-05T22:14:58Z

[[affected.golang]]
name = "stdlib"

[[affected.golang.imports]]
path = "crypto/x509"
symbols = [ "Certificate.Verify", "Certificate.buildChains" ]

[[affected.golang.version.ranges]]
fixed = "1.21.8"

[[affected.golang.version.ranges]]
introduced = "1.22.0-0"
fixed = "1.22.1"
