# WIP
# CVE-2023-22081
# component = security-libs/javax.net.ssl

[[affected.java]]
name = "jre"
components = ["security-libs/javax.net.ssl"]

[[affected.java.version.ranges]]
fixed = "1.8.0_392"

[[affected.java.version.ranges]]
introduced = "1.9"
fixed = "11.0.21"

[[affected.java.version.ranges]]
introduced = "12"
fixed = "17.0.9"

[[affected.java.version.ranges]]
introduced = "18"
fixed = "21.0.1"