[sources.cve]
id = "CVE-2024-2126"
url = "https://cveawg.mitre.org/api/cve/CVE-2024-2126"
published = "2024-03-13T15:26:32.648Z"
modified = "2024-03-13T15:26:32.648Z"

[sources.github]
id = "GHSA-99x8-5v72-mr3c"
url = "https://raw.githubusercontent.com/github/advisory-database/ec9ff50b1a1b64a1b52978aff5a3ccb560e90933/advisories/unreviewed/2024/03/GHSA-99x8-5v72-mr3c/GHSA-99x8-5v72-mr3c.json"
published = "2024-03-13T18:31:35Z"
modified = "2024-03-13T18:31:35Z"

[[affected.wordpress-plugin]]
# I chose this one specifically because it illustrates some of the issues with the Wordpress plugin
# ecosystem that we'll need to think more about.
# Name is taken from the `Plugin Name` header of the main php file for the plugin: 
# https://plugins.trac.wordpress.org/browser/themeisle-companion/trunk/themeisle-companion.php#L15
# 
# Per the spec `Plugin Name` is the only required field: https://developer.wordpress.org/plugins/plugin-basics/header-requirements/#minimum-fields
# 
# However, as far as uniqueness goes, this plugin is available from https://wordpress.org/plugins/themeisle-companion
# notice the id here matches the `Text Domain` header: https://plugins.trac.wordpress.org/browser/themeisle-companion/trunk/themeisle-companion.php#L23
# 
# It seems common that the text `Text Domain` header tends to correspond to the `Plugin Name`
# in all lowercase with `-` replacing spaces, but that isn't a guarantee
#
# I expect the best patch forward here for the moment at least is to specify both plugin name and 
# text domain when present.  There is also a concept of Update URI: which can be specified when 
# using a repository other than wordpress.org, but that too seems to vary widely (this particular example 
# specifies a different Update URI even while it is distributed via wordpress.org
# 
# We should also investigate if the main plugin file is always named the same as the package slug in the
# url, so in this case `themeisle-companion.php`.  It seems like wordpress understands the plugin slug from the
# project layout per the examples in https://github.com/anchore/syft/issues/1911, but warrants further investigation
name = "Orbit Fox Companion"
slug = "themeisle-companion"

[[affected.wordpress-plugin.version.ranges]]
fixed = "2.10.33"
